### ISSUE TITLE
Comments from the /r/rust thread

### ISSUE THREAD

**Issue by gnzlbg** [vmchale/ats-benchmarks#1]
In the /r/rust thread: https://www.reddit.com/r/rust/comments/7pe925/more_examples_of_haskell_running_5x_faster_than/

people mentioned that:

- [ ]  the factorials implementation in haskell is memoized (factorials is filled lazily and is allowed to stay live indefinitely) but the Rust one isn't
- [ ] the ramp implementation has a bug (`factorials_ramp(0)` returns `0` instead of `1`)
- [ ] ramp types support `AddAssign` (`+=`) which is faster than `+`.
- [ ] the links in your blog are hard to recognize visually, so people had trouble finding this repo to see the code and figure out what's going on.

Thought I would mention these here in case you hadn't seen the thread, good work! I liked the article!

**Comment by vmchale** [comment]
Explanations regarding caching and how to verify results [here](http://blog.vmchale.com/article/haskell-faster). 

Not really sure where `+=` would be useful.

**Comment by Veedrac** [comment]
You can check that it's memoized by `Debug.Trace.trace`ing the multiplication if you're skeptical.
